version: '3.7'
services:
  ignite-api:
    build:
      context: .
      dockerfile: backend.docker
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - 3000:3000
    depends_on:
      - ignite-dds-postgres
    volumes:
    - /app/node_modules
  ignite-dds-postgres:
    init: true
    image: postgres:12.2-alpine
    volumes:
      - ignite-dds-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_DOCKER_PORT}:5432
  ignite-dds-pgadmin:
    init: true
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - ignite-dds-postgres
  main_net:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --networkId
      - '5555'
      - -e
      - '10000'
volumes:
  ignite-dds-postgres:
  ganache_data:
